Criação de projeto e setup das configurações
gmr-tech/pokedex_app_template pull request #1
Opened 2023-07-20 16:30 UTC by igorMaldonado10

### Descrição

Este pull request tem como objetivo realizar a criação do projeto Flutter e adicionar as seguintes configurações:

1. Adição de dependências para medir a qualidade do código fonte e fornecer informações sobre métricas e boas práticas de programação.
1. Implementação da base do tema claro e escuro, juntamente com um switcher para alternar entre eles.
1. Criação do package do Design System, contendo todas as informações relevantes ao design do projeto.
1. Configuração do FVM (Flutter Version Management) para garantir a consistência da versão do Flutter entre a equipe de desenvolvimento.

### Alterações propostas

* Adiciona as dependências necessárias no arquivo pubspec.yaml para análise estática de código e gerência de estado do tema.
* Define os estilos básicos para o tema claro e escuro e implementa a funcionalidade de alternância entre eles.
* Cria um novo package chamado `design_system`, que inclui componentes reutilizáveis, estilos compartilhados e recursos de design para o projeto.
* Configura o FVM para que a equipe de desenvolvimento utilize a mesma versão do Flutter no projeto.

### Contexto

Com essa estrutura inicial, buscamos garantir a qualidade do código e estabelecer um padrão de design consistente em todo o projeto. O uso do Design System facilitará a reutilização de código, tornará a manutenção mais eficiente e permitirá a escalabilidade do projeto à medida que novos recursos são adicionados. A configuração do FVM visa manter a consistência nas versões do Flutter, garantindo que todos os desenvolvedores estejam trabalhando na mesma base.

### Revisores específicos

@gmr-renato

2023-07-21 18:46 UTC, gmr-renato commented
@igorMaldonado10 algumas coisas que você precisa fazer:

- Coloque o código da tarefa mãe no título do PR. Ex. : PAT-19: Criação do projeto e setup das configurações
- Se atribua como Assignee do PR
- Me coloque como Reviewer do PR
- Se o código feito gerar imagens ou items visuais no app, adicione imagens e vídeos que mostrem esse funcionamento.

2023-07-21 19:03 UTC, gmr-renato requested changes
120/192 Arquivos revisados.

Já subi algumas perguntas e sugestões que você pode ir corrigindo.

2023-07-25 16:01 UTC, gmr-renato commented on design_system/README.md
Reescreva a resposta com suas próprias palavras por favor.

2023-07-25 16:02 UTC, gmr-renato commented on design_system/android/local.properties
Se eles não precisão ser compartilhados no controle de versão, remova os do PR usando o gitIgnore por favor.

2023-07-26 13:24 UTC, igorMaldonado10 commented on design_system/lib/src/theme/base/ds_dark_theme.dart
> +/// usado para personalizar a aparência da aplicação em um tema escuro.
O problema mencionado foi corrigido. Agora, as variáveis são documentadas com comentários imediatamente acima das classes variáveis. Não estão mais sendo colocadas no final do arquivo.

2023-07-26 13:57 UTC, igorMaldonado10 commented on design_system/android/local.properties
O problema foi corrigido. O arquivo foi removido do PR (Pull Request) usando o gitignore.

2023-07-26 14:04 UTC, igorMaldonado10 commented on design_system/lib/src/theme/base/ds_light_theme.dart
> +///esse arquivo define um esquema de cores e um conjunto de dados de tema claro
O problema mencionado foi corrigido. A documentação não está mais localizada no final do arquivo.

2023-07-26 14:43 UTC, gmr-renato requested changes
Algumas alterações ainda são necessárias.

2023-07-26 17:07 UTC, igorMaldonado10 commented on test/widget_test.dart
Estes testes estão funcionando sim. E para verificar se eles estão funcionando, primeiramente, é necessário verificar se o arquivo de teste está configurado corretamente, ou seja, se as dependências corretas estão instaladas e se as importações correspondentes aos arquivos que serão testados foram realizadas, seguindo, você pode executar os testes por meio da própria interface do VSCode voltado para a execução de testes chamada: "testing" ou também executar os testes usando o comando `flutter test` no terminal. Após isso você deve observar a saída do teste no console para verificar se eles passaram ou falharam.

2023-07-27 03:12 UTC, gmr-renato requested changes

2023-07-27 03:12 UTC, gmr-renato commented on lib/src/common/presentation/app_assets.dart
> +library;
```suggestion
```

Essa linha não é necessária

2023-07-27 03:14 UTC, gmr-renato commented on test/widget_test.dart
Para respostas em PRs de projetos templates evite enviar os textos sugeridos por IAs. Eles são muito "padrão" e fica quase impossível de eu validar se você sabe sobre o que está falando ou não.

2023-07-27 12:24 UTC, igorMaldonado10 commented on lib/src/common/presentation/app_assets.dart
> +library;
Alteração sugerida realizada.

2023-07-27 12:24 UTC, igorMaldonado10 commented on test/widget_test.dart
Ok, entendido.

2023-07-27 20:09 UTC, gmr-renato requested changes
As documentações precisam ser corrigidas

2023-07-27 20:09 UTC, gmr-renato commented on design_system/lib/design_system.dart
> +///As declarações `export` são usadas para exportar definições
Adicionar espaço em as 3 barras e a palavra. Corrigir Isso para todos os arquivos.

2023-07-27 20:13 UTC, gmr-renato commented on design_system/lib/design_system.dart
> +///As declarações `export` são usadas para exportar definições
@igorMaldonado10 tem um jeito de fazer isso sem precisar alterar todos os comentários, um por. Uma dica é usar a aba "Search"do VSCode para te ajudar.

2023-07-27 20:35 UTC, igorMaldonado10 commented on design_system/lib/design_system.dart
> +///As declarações `export` são usadas para exportar definições
Espaço adicionado em cada documentação. Feito!

2023-07-27 21:21 UTC, gmr-renato requested changes

2023-07-27 21:21 UTC, gmr-renato commented on design_system/lib/src/theme/base/ds_theme_controller.dart
> +///     DSThemeMode _dsThemeMode = DSThemeMode.dark;
A documentação dos elementos de uma classe deve ser feita direto sobre o elemento. Desse jeito aqui, todo esse texto aparece quando você passa o mouse sobre a classe, e nenhum texto aparece quando você passa o mouse sobre o elemento. Mova-os para o local correto por favor.

2023-07-27 21:21 UTC, gmr-renato commented on design_system/lib/src/theme/custom/ds_color.dart
> +/// dois temas disponíveis para personalização: "light" e "dark".
Escreva com suas próprias palavras por favor. Lembrando que o intuito é fazer uma documentação que explique o por que das coisas, não o que. E eu estou usando essas explicações para verificar se você entendeu o que está copiando.

2023-07-27 21:21 UTC, gmr-renato commented on design_system/lib/src/theme/custom/ds_custom_theme.dart
> +///
Idem^

2023-07-27 21:21 UTC, gmr-renato commented on design_system/lib/src/theme/custom/ds_typography.dart
> +///
Idem^

2023-07-28 11:06 UTC, igorMaldonado10 commented on design_system/lib/src/theme/custom/ds_color.dart
> +/// dois temas disponíveis para personalização: "light" e "dark".
Certo, entendido. As alterações foram realizadas como desejado.

2023-07-28 11:06 UTC, igorMaldonado10 commented on design_system/lib/src/theme/custom/ds_custom_theme.dart
> +///
Alterações realizadas no arquivo.

2023-07-28 11:06 UTC, igorMaldonado10 commented on design_system/lib/src/theme/custom/ds_typography.dart
> +///
Alterações realizadas no arquivo.

2023-07-28 15:13 UTC, gmr-renato approved these changes
Aprovado!

2023-07-28 15:14 UTC, merged