PAT-20: Criação da camada de domínio compartilhada
gmr-tech/pokedex_app_template pull request #2
Opened 2023-08-04 11:20 UTC by igorMaldonado10

## Descrição

Este pull request tem como objetivo realizar a criação da camada de domínio do projeto, juntamente com os arquivos e subpastas destinados a essa camada, além da adição das seguintes dependências:

1. `build_runner: ^2.4.6` : uma dependência que nos permite gerar classes imutáveis (immutable) com base em anotações.
2. `freezed: ^2.4.0` : uma dependência que auxilia na geração de código automatizada, incluindo o código necessário para as classes imutáveis criadas pelo freezed.
3. `freezed_annotation: ^2.2.0` : As anotações necessárias para o uso do freezed.

## Alterações propostas

* Adiciona as dependências necessárias no arquivo `pubspec.yaml`  para a geração do código usando o freezed;
* Criação das entities da camada;
* Criação das regras de negócio.

## Contexto

Neste pull request, foi criado a camada de domínio do projeto, que é uma parte importante da arquitetura. Essa camada contém as regras de negócio, entidades e a lógica central do aplicativo. 

Foi criada uma pasta chamada 'entities' para guardar os modelos dos objetos importantes do projeto. Esses modelos garantem que o aplicativo funcione de forma independente dos detalhes de implementação.

Além disso, foi adicionado dependências para geração de código, o que é útil para agilizar o desenvolvimento e manter o código consistente em todo o projeto. Com a geração de código, é possível criar classes, métodos e outras estruturas de maneira automática, reduzindo erros manuais e aumentando a produtividade.

## Revisores específicos

@gmr-renato

2023-08-04 14:18 UTC, gmr-renato requested changes
2 pequenas sugestões

2023-08-04 14:18 UTC, gmr-renato commented on lib/src/common/domain/entities/pokemon_type.dart
> +  /// Aqui temos um construtor constante da classe, ou seja, após ter sido
Isso é uma classe?

2023-08-04 14:18 UTC, gmr-renato commented on lib/src/common/domain/sorting_order.dart
> +  /// condicional if/else.
Isso aqui não está correto. Você precisa entender melhor essa função para criar a documentação.

2023-08-04 22:47 UTC, igorMaldonado10 commented on lib/src/common/domain/entities/pokemon_type.dart
> +  /// Aqui temos um construtor constante da classe, ou seja, após ter sido
Não, isso não é uma _**classe**_. Se trata de um _**enum**_ com valores constantes e bem definidos, diferente de uma _**classe**_ que é um conjunto de atributos e métodos que não necessariamente são constantes. 

Sendo assim, vou realizar uma atualização na documentação que faz entender o contrário sobre o arquivo.

2023-08-04 22:47 UTC, igorMaldonado10 commented on lib/src/common/domain/sorting_order.dart
> +  /// condicional if/else.
Entendido. Realizei uma atualização referente a essa a documentação.

2023-08-10 11:06 UTC, gmr-renato requested changes

2023-08-10 11:06 UTC, gmr-renato commented on lib/src/common/domain/sorting_order.dart
> +/// que eles atuam como se fossem enumerações também.
## 1 ##

Documentações e comentários pode conter 3 conceitos básicos:

- O que? (Inútil)
- Como? (Inútil)
- Por que? (Útil)

Parte dessa documentação aqui explica "o que foi feito" e o "como foi feito". Isso não é necessário, as documentações devem explicar o por que está sendo feito, apenas.

Sendo assim, revise sua documentação e comentários criados para conter apenas os "por quês", somente aonde for necessário, os "o quês" e "comos" devem estar explícitos no próprio código.

2023-08-10 11:06 UTC, gmr-renato commented on lib/src/common/domain/sorting_order.dart
> +  /// de A à Z;
## 2 

Esse comentário não faz o menor sentido. "Construtor de fábrica"?

2023-08-10 11:06 UTC, gmr-renato commented on lib/src/common/domain/sorting_order.dart
> +  ///  de Z à A;
2 ^

2023-08-10 11:06 UTC, gmr-renato commented on lib/src/common/domain/sorting_order.dart
> +  /// em ordem crescente.
2 ^

2023-08-10 11:06 UTC, gmr-renato commented on lib/src/common/domain/sorting_order.dart
> +/// `SortingOrder.byNameAZ()`.
1 ^

Ainda contém coisa errada aqui.

2023-08-10 11:06 UTC, gmr-renato commented on lib/src/common/domain/sorting_order.dart
> +  /// diferente de `SortingOrder.byNameAZ()`, o getter retornará false.
1 ^

2023-08-10 11:06 UTC, gmr-renato commented on lib/src/common/domain/sorting_order.dart
> +  /// diferente de `SortingOrder.byNameZA()`, o getter retornará false.
1 ^

2023-08-10 11:06 UTC, gmr-renato commented on lib/src/common/domain/sorting_order.dart
> +  /// retornará false.
1 ^

2023-08-10 11:06 UTC, gmr-renato commented on lib/src/common/domain/sorting_order.dart
> +  /// retornará false.
1 ^

2023-08-10 11:06 UTC, gmr-renato commented on lib/src/common/domain/sorting_order.dart
> +  /// o tipo de ordenação representada.
1 ^

2023-08-11 18:25 UTC, gmr-renato approved these changes
Aprovado. Pode seguir para o próximo item.

2023-08-11 18:26 UTC, merged