PAT-31: Pokelist
gmr-tech/pokedex_app_template pull request #5
Opened 2023-09-23 05:05 UTC by igorMaldonado10

## Descrição 

Este pull request tem como objetivo criar a camada de domain e infrastructure na feature pokelist. Na camada de domain, foi criada uma classe abstrata para a criação do repositório da Pokelist. Na camada de infrastructure, foi implementado o repositório da feature Pokelist. Além disso, foram feitas as seguintes mudanças:

* Atualização da pasta common: foram criados objetos DTO (Data Transfer Objects) e um arquivo de tratamento de exceções HTTP chamado `GlobalHandleException`.

* Inicialização da implementação do package **GoRouter** a partir das configurações de cada rota.

* Inicialização da instância singleton do **GoRouter** e armazenamento das rotas utilizadas na navegação do aplicativo de forma constante.

## Alterações propostas

* Criação da camada de domain e infrastructure na feature pokelist.
* Criação dos DTO\`s   e o arquivo `GlobalHandleException`  na pasta common.
* Habilitação da barra de pesquisa na app bar com filtros por nome e ID do Pokémon.
* Configuração do [GoRouter](https://pub.dev/packages/go_router).
* Implementação do filtro por tipo de Pokémon através de chips dentro do modal.
* Adição da dependência [Alchemist](https://pub.dev/packages/alchemist) para realizar os golden tests.
* Criação dos golden tests da Pokelist feature.

## Contexto

Neste pull request, foi criada as camadas de domain e infrastructure da feature pokelist. A camada de domain é responsável por definir a estrutura geral do repositório da Pokelist, enquanto a camada de infrastructure trata da implementação concreta desse repositório.

Na pasta common, foi feito melhorias importantes, incluindo a criação de objetos DTO para facilitar a transferência de dados e a implementação de um tratamento de exceções HTTP com o arquivo `GlobalHandleException`.

Além disso, foi iniciado a implementação do package **GoRouter para** gerenciar a navegação no aplicativo. Isso inclui a configuração das rotas e a inicialização da instância singleton do **GoRouter**. Também foi armazenado de forma constante as rotas usadas na navegação.

As alterações propostas incluem a habilitação da barra de pesquisa na app bar, que permite aos usuários filtrar o Pokémon por nome e ID. Também foi habilitado o filtro por tipo de Pokémon usando chips dentro do modal.

Por fim, foi adicionado a dependência **Alchemist** para realizar os golden tests, para garantir a fidelidade com a referência da interface do usuário.

## Vídeo de comparação

https://github.com/gmr-tech/pokedex_app_template/assets/109998678/223f8cf4-5fab-4cc2-8767-189ddc15b7fc

## Revisores específicos

@gmr-renato

2023-09-25 05:47 UTC, gmr-renato requested changes
36 de 89 arquivos revisados. Você ja consegue ir trabalhando em algumas correções.

2023-09-25 05:50 UTC, gmr-renato commented
@igorMaldonado10 antes de continuar, percebi que sua branch `feat/PAT-31` tem conflitos a com develop-igor. Romendo que você dê merge da `develop-igor` para a branch `feat/PAT-31` e resolva os conflitos antes de trabalhar nas alterações.

2023-09-25 16:41 UTC, igorMaldonado10 commented on lib/src/features/pokelist/application/pokelist_controller.dart
> +  final List<Pokemon> _allPokemons = [];
Documentação atualizada.

2023-09-25 19:25 UTC, gmr-renato requested changes
Pequenas mudanças

2023-09-25 19:25 UTC, gmr-renato commented on test/src/features/pokelist/presentation/ui_components/failures/pokemon_list_card_isolatedDiff.png
Excluir

2023-09-25 19:25 UTC, gmr-renato commented on test/src/features/pokelist/presentation/ui_components/failures/pokemon_list_card_maskedDiff.png
^

2023-09-25 19:25 UTC, gmr-renato commented on test/src/features/pokelist/presentation/ui_components/failures/pokemon_list_card_masterImage.png
^

2023-09-25 19:25 UTC, gmr-renato commented on test/src/features/pokelist/presentation/ui_components/failures/pokemon_list_card_testImage.png
^

2023-09-25 19:25 UTC, gmr-renato commented on test/src/features/pokelist/presentation/ui_components/grid_view_for_testing.dart
> +// Used to build pokelist gridview in tests
Traduzir ou excluir

2023-09-26 11:43 UTC, igorMaldonado10 commented on lib/src/common/presentation/common_present_const.dart
> +  /// Standard debounce time for user input in milliseconds
Documentação traduzida.

2023-09-26 11:43 UTC, igorMaldonado10 commented on test/src/features/pokelist/presentation/ui_components/failures/pokemon_list_card_isolatedDiff.png
Imagem excluída do projeto.

2023-09-26 11:43 UTC, igorMaldonado10 commented on test/src/features/pokelist/presentation/ui_components/failures/pokemon_list_card_maskedDiff.png
Imagem excluída.

2023-09-26 11:43 UTC, igorMaldonado10 commented on test/src/features/pokelist/presentation/ui_components/failures/pokemon_list_card_masterImage.png
Imagem excluída.

2023-09-26 11:43 UTC, igorMaldonado10 commented on test/src/features/pokelist/presentation/ui_components/failures/pokemon_list_card_testImage.png
Imagem excluída.

2023-09-26 11:43 UTC, igorMaldonado10 commented on test/src/features/pokelist/presentation/ui_components/grid_view_for_testing.dart
> +// Used to build pokelist gridview in tests
Documentação atualizada com a tradução.

2023-09-26 13:01 UTC, gmr-renato approved these changes
Aprovado

2023-09-26 13:08 UTC, merged